<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { getConvexClient } from 'convex-svelte';
	import { authStore } from '$lib/auth.svelte.js';

	let status = $state<'loading' | 'error'>('loading');
	let errorMessage = $state('');

	onMount(async () => {
		const code = $page.url.searchParams.get('code');
		const verifier = $page.url.searchParams.get('verifier');

		if (!code || !verifier) {
			await goto('/');
			return;
		}

		try {
			const client = getConvexClient();
			// auth:signIn is generated by @convex-dev/auth after `npx convex dev`
			// eslint-disable-next-line @typescript-eslint/no-explicit-any
			const result = await client.action('auth:signIn' as any, {
				provider: 'google',
				params: { code, verifier },
			});

			if (result?.tokens?.token) {
				authStore.setToken(result.tokens.token, result.tokens.refreshToken);
			}

			await goto('/');
		} catch (e) {
			status = 'error';
			errorMessage = e instanceof Error ? e.message : 'Sign-in failed.';
		}
	});
</script>

{#if status === 'loading'}
	<div class="auth-status">Completing sign-in…</div>
{:else}
	<div class="auth-status error">
		<p>Sign-in failed: {errorMessage}</p>
		<a href="/">Return home</a>
	</div>
{/if}

<style>
	.auth-status {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		min-height: 50vh;
		font-family: var(--font-body, sans-serif);
		gap: 1rem;
	}
	.error {
		color: #c0392b;
	}
</style>
